# Generated by Django 5.2.1 on 2025-05-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_passtemplate_remove_pass_template_used_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуски'},
        ),
        migrations.AlterModelOptions(
            name='passtemplate',
            options={'verbose_name': 'Шаблон пропуска', 'verbose_name_plural': 'Шаблоны пропусков'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='generated_document',
            field=models.FileField(blank=True, null=True, upload_to='passes/', verbose_name='Сгенерированный документ'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='purpose',
            field=models.TextField(verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passes.passtemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='passtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='passtemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='passtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='passtemplate',
            name='template_file',
            field=models.FileField(upload_to='templates/', verbose_name='Файл шаблона'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
    ]
